### ISSUE TITLE
Put downloads in Github release instead of branch

### ISSUE THREAD

**Issue by gdevenyi** [eborisch/LCModel#1]
See https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by eborisch** [comment]
I've created releases of both the upstream per-compiled binaries as well as for the source code.

Note I have no plans for active development here; this was for safekeeping of the code (in the event the upstream website ever disappears.)

**Comment by gdevenyi** [comment]
Thanks so much. I get that, I hope someone can take this on.
